/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.7.1/userguide/multi_project_builds.html
 */

rootProject.name = "fastcampus-spring-cloud"

include(
        "fastcam-spring-utils",
        "fastcam-spring-eureka",
        "fastcam-spring-apigw",
        "fastcam-photoapp",
        "fastcam-spring-rabbitmq",
        "fastcam-spring-kafka",
        "fastcam-resilience4j",
        "fastcam-resilience4j-server",
        "fastcam-feignclient",
        "fastcam-spring-config",
        "fastcam-spring-config-consumer",
        "fastcam-spring-admin",
        "fastcam-spring-sleuth",
        "fastcam-spring-vault")

