server.port: 9093

# config server property yml file name

management:
  endpoints:
    web:
      exposure:
        include: ['refresh','beans','env']

logging:
  level:
    org.springframework: TRACE
